### PR TITLE
Changes in UI

### PR DESCRIPTION
**Pull request by muskankhedia**
#5 Now the message sent by the user is shown on the right side whereas the response from the server is displayed on the left side with some modification in the message box radius.
Screenshot at 2019-04-02 01-11-22

### CODE REVIEW

**Comment by Harkishen-Singh** [comment]
please resolve the conflicts, @muskankhedia

**Comment by muskankhedia** [comment]
Yaa.. working on it.

**Comment by Harkishen-Singh** [comment]
> Please merge it.

already merged, my girlfriend!

**Comment by muskankhedia** [comment]
> > Please merge it.
> 
> already merged, my girlfriend!

Love you...Thank you...

**Pull request merged**
