### PR TITLE
Mockup for Home page UI

### PR DESCRIPTION
**Pull request by SubCoder1**
This PR solves issue https://github.com/Harkishen-Singh/Jarvis-personal-assistant/issues/161

**What does this PR do?**
It has the proposed mockups of Home page UI created with Figma as suggested.

**Any background context you want to provide?**
The links added in the files are connected to the UI prototype.
2 files have been added in this PR, ```ui-design--1-dark.txt ``` has Dark mode theme enabled in the prototype itself, and ```ui-design--1-light.txt``` has the traditional white mode theme.

**Screenshots?**
None

### CODE REVIEW

**Comment by muskankhedia** [comment]
@SubCoder1 UI looks fine. But some changes to be made like we want the background colour to be white itself. Any other colour doesn't look that eye-catching and clear. So please change it to white. And regarding the message icon at the top. Something better can be implemented. And also there should be horizontal bar below the message icon.

**Comment by muskankhedia** [comment]
The Get Help section has already been implemented and in PR#172, you can have a look and implement something similar to match the theme and get a unified experience.

**Comment by SubCoder1** [comment]
@muskankhedia Thank you for reviewing, I've integrated the chosen theme from PR https://github.com/Harkishen-Singh/Jarvis-personal-assistant/pull/172, changed the chat icon on-top and added a horizontal bar too. kindly re-open the link to check the changes. :)

**Comment by muskankhedia** [comment]
The present UI  looks fine to me. What do you say @lalitmee @Harkishen-Singh @prashant-mahanta ?

**Comment by lalitmee** [comment]
Yeah it's looking great.

**Pull request merged**
