### PR TITLE
Added Github login form and ui improvements

### PR DESCRIPTION
**Pull request by Subham-Mishra**
Capture

### CODE REVIEW

**Comment by muskankhedia** [comment]
Please pull the changes before git push, as now the number of files changed is 176, and its difficult to review the particular code which is changed in the commits.
Can you add another fileld for root password of the user ?

**Comment by Subham-Mishra** [comment]
I did pull the changes before pushing but its showing Already up to date... No need to review all files Can u please just run this code if all funtionalities added afterwards are working then merge it
[Capture](https://user-images.githubusercontent.com/35756816/55274528-666bf500-52ff-11e9-841e-4837a8ebf236.JPG)

**Comment by Subham-Mishra** [comment]
Capture

**Comment by Subham-Mishra** [comment]
Capture

**Comment by Harkishen-Singh** [comment]
@Subham-mishra , u have changed the location of many files, and hence it's showing 126 files changes. Like, u have brought the js folder to the root of the project, which was earlier inside view folder.

**Comment by Harkishen-Singh** [comment]
Hence, make the js folder inside the view folder when it was earlier, and commit again. Then note, the number of file changed should be decreased to only the files u have updated the code with.

**Comment by Subham-Mishra** [comment]
Please close this PR ...i have sent a new PR with modification

**Pull request closed without merging**
