### PR TITLE
Added yahoo scrapping with golang

### PR DESCRIPTION
**Pull request by irshadjsr21**
This PR solves issue #138 

**What does this PR do?**
Added yahoo scrapping with golang

**Screenshots?**
Screenshot from 2020-03-16 03-15-46

### CODE REVIEW

**Comment by irshadjsr21** [comment]
@muskankhedia The code is working, it is just that sometimes Yahoo server rejects the request. You can check the build log, it failed one time and ran for another.

**Comment by prashant-mahanta** [comment]
@irshadjsr21 can't we do something like requesting until we get results.

**Comment by muskankhedia** [comment]
> @irshadjsr21 can't we do something like requesting until we get results.

Yaa.. for that reason only we use `selenium` or `puppeteer`, as these open a virtual browser and waits till the page has been loaded. But for now, we are planning to remove these kind of dependencies so as to avoid different circumstances while launching as well creating a single method to execute all the feature.

**Comment by irshadjsr21** [comment]
@muskankhedia So what should I do now?

**Comment by muskankhedia** [comment]
@irshadjsr21 Let the implementation in Golang for now, will enhance it later.

**Comment by Harkishen-Singh** [comment]
@irshadjsr21 can you fix the Travis?

**Comment by irshadjsr21** [comment]
@Harkishen-Singh The code runs on my system, I think it will work if we rebuild it.

**Comment by C-Anirudh** [comment]
@irshadjsr21 Please resolve the merge conflicts.

**Comment by irshadjsr21** [comment]
@C-Anirudh The conflicts has been resolved,

**Comment by muskankhedia** [comment]
@irshadjsr21 The testing files have been updated presently. Can you pull the recent updates to test the PR?

**Comment by muskankhedia** [comment]
@irshadjsr21 The PR is good to go just pull the recent files and tests as the PR couldn't be merged until the tests have been passed.

**Pull request merged**
