### PR TITLE
Enhanced the UI for youtube results and added description for images

### PR DESCRIPTION
**Pull request by muskankhedia**
#64 
1. The UI for youtube results have been enhanced and now the videos are displayed on the web page itself.

2. Added the description for images from google images by scrapping the HTML code.

**A view of the youtube search**

Screenshot at 2019-05-03 14-05-14

### CODE REVIEW

**Comment by muskankhedia** [comment]
@Harkishen-Singh pls have a view

**Comment by muskankhedia** [comment]
@Harkishen-Singh please check it. It's pending for long. And pls suggest if any changes required

**Comment by Harkishen-Singh** [comment]
Sure. Will check as soon as possible

**Comment by muskankhedia** [comment]
Thank you.

**Pull request merged**
