### PR TITLE
Improved INSTALL.md, fixed some typos

### PR DESCRIPTION
**Pull request by prajwal714**

### CODE REVIEW

**Comment by C-Anirudh** [comment]
@prajwal714 The `INSTALL.md` file has been updated, please have a look.

**Comment by lalitmee** [comment]
@prajwal714 , there are some conflicting changes in your **PR**. Please resolve the conflicts. :+1:

**Comment by ananyaarun** [comment]
Hey @prajwal714 , Do you need any help ? Feel free to ask us !

**Comment by Harkishen-Singh** [comment]
@muskankhedia are we closing this?

**Comment by muskankhedia** [comment]
Yaa.. the readme has been completely updated now.

**Pull request closed without merging**
