### PR TITLE
Enhanced recent queries section

### PR DESCRIPTION
**Pull request by robot-with-feelings**
This PR solves issue #186 

The 'Recent Queries' section was modified so that it is not confused with a button. 

The 2 samples created using Figma are:

Recent Queries
Recent Queries 2

### CODE REVIEW

**Comment by robot-with-feelings** [comment]
@muskankhedia done!

**Comment by muskankhedia** [comment]
I think the message has been conveyed wrong, I asked you to change the folder with name 'ui-designs' to 'ui-wireframe-desktop'. Please make the change.

**Comment by robot-with-feelings** [comment]
@muskankhedia oops!

**Comment by robot-with-feelings** [comment]
changed the names again now

**Pull request merged**
