### PR TITLE
Added images search feature 

### PR DESCRIPTION
**Pull request by muskankhedia**
#10 The image search has been added in this PR. Now the user can make image search using Personal Assistant, the syntax of search is **image content**. Also on clicking on the image, the full-size image will be displayed in the other tab.
The features are better explained in the video. To watch the video [click here.](https://drive.google.com/file/d/1ncee5Rx6wEDyeQSWycTmUSjVhgNgq4vp/view)

### CODE REVIEW

**Comment by Harkishen-Singh** [comment]
is this PR ready for review? have all the pre-work completed?

**Comment by muskankhedia** [comment]
Yes, Pls check the video and pls suggest the changes required.

**Comment by Harkishen-Singh** [comment]
Good work! clean code, merging!

**Comment by muskankhedia** [comment]
Thank you !!

**Pull request merged**
