### PR TITLE
Added Mockup for Get Help UI

### PR DESCRIPTION
**Pull request by robot-with-feelings**
This PR solves issue #162 

Created 5 different mockups for the UI:
 

Get Help Section 1
Get Help Section 4
Get Help Section 5
Get Help Section 2
Get Help Section 3

### CODE REVIEW

**Comment by Harkishen-Singh** [comment]
These look really appealing. Thank you for this @robot-with-feelings .

**Comment by Harkishen-Singh** [comment]
For now, let's have anyone with mutual discussion. Later, we can add an option for theme selection as a dropdown.

**Comment by muskankhedia** [comment]
I would like to go up with the 5th UI in the description. What do you say @Harkishen-Singh @lalitmee @prashant-mahanta?

**Comment by Harkishen-Singh** [comment]
5th is good for me.

**Comment by prashant-mahanta** [comment]
The 2nd and 5th seem good to me.

**Comment by muskankhedia** [comment]
> The 2nd and 5th seem good to me.

I don't think we should prefer any other background colour other than white as of now.

**Comment by muskankhedia** [comment]
The 5th UI design in the description looks good to us. Will you be interested to implement the code in the next PR?

**Comment by robot-with-feelings** [comment]
sure, i'm on it !

**Pull request merged**
