### PR TITLE
added home-page-UI implementation --test

### PR DESCRIPTION
**Pull request by SubCoder1**
This PR solves issue https://github.com/Harkishen-Singh/Jarvis-personal-assistant/issues/184

**What does this PR do?**
Complete implementation of Home-Page-UI using HTML5, CSS3, JQuery, Bootstrap4.

**Any background context you want to provide?**
I've made the send message button functional using JQuery --front-end. All the files are inside ```view->web->home-page-ui``` folder and can be viewed by opening index.html. I'll place all the files in their respective folders when no further changes are required.

**Screenshots?**
Screenshot (43)

### CODE REVIEW

**Comment by SubCoder1** [comment]
@muskankhedia I understood the part of integrating all of the new files with existing files, but i didn't understand the Help-UI issue you mentioned. Can you please elaborate?

**Comment by muskankhedia** [comment]
@SubCoder1 There has been a conflict now, issue #183 corresponds for the implementation of the Get Help UI section, and another member is already working on it. As you have also worked hard implementing different sections, so for now, you can just comment the particular part of code and will decide about the ongoings once the PR for that issue has been made.

**Comment by SubCoder1** [comment]
@muskankhedia So you want me to comment out my part of code just for now? And, it does mean all of my css, html & other codes right?

**Comment by muskankhedia** [comment]
@SubCoder1 yes, and commenting only HTML code will work fine.

**Comment by SubCoder1** [comment]
@muskankhedia Sure, will do :)

**Comment by SubCoder1** [comment]
@muskankhedia  I'm having problems regarding integrating my files with the ones existing.
**-Questions-**
1. Should I copy/paste all of my CSS codes to the existing main.css or create a new one? because 
    there might be conflicts.
2. Which part of index.html (existing) should I replace my index.html code with?

**Comment by muskankhedia** [comment]
@SubCoder1 You need to carefully integrate each and every section with the index.html file. It is recommended to copy specific parts of CSS with the respective html codes while implementing the UI. So please don't copy the entire file as it may increase a lot of work and will make difficult to implement.

**Pull request merged**
