### PR TITLE
Updated README.md with Postman doc link

### PR DESCRIPTION
**Pull request by CSElonewolf**
previous commit:-
Annotation 2020-03-09 175000

new commit:-

Annotation 2020-03-09 180942

This PR solves issue #149 

**Files Added/Updated**
Added Postman Documentation Link to README.md

@muskankhedia and @Harkishen-Singh Please review and let me know if any changes to be made

### CODE REVIEW

**Comment by muskankhedia** [comment]
It looks good. Just make a minor change, and place it before achievements.

**Comment by CSElonewolf** [comment]
@muskankhedia  look at the new commit and kindly assign me that issue or maybe there can be some conflict with the GSSoC points.

**Comment by muskankhedia** [comment]
@CSElonewolf Good work! Thanks for making the changes so soon. And regarding  GSSoC you won't get points on assigning the issues. Points are being rewarded on merged PRs with labels of GSSoC-20 on it, so don't be worried regarding the issue assigning part.

**Comment by muskankhedia** [comment]
@CSElonewolf Good work! Thanks for making the changes so soon. And regarding  GSSoC you won't get points on assigning the issues. Points are being rewarded on merged PRs with labels of GSSoC-20 on it, so don't be worried regarding the issue assigning part.

**Comment by muskankhedia** [comment]
@CSElonewolf As you are new to Open Source Development, I should say you some points that you should keep in mind while contributing. 
1. Do comment to every issue before starting to work on it.
2. Please wait for the maintainer or mentors to approve or assign the issue, many times some already solved issue hasn't been closed and your work may go in  vain.
3. And thirdly, if any issue has already been assigned to anyone please just don't make the PR early that it will be accepted, the mentor can easily reject the PR as the issue was already assigned to someone else and your work won't be considered.

You have done good work and thanks for making the changes so early which others were taking days to do. And as you are new and haven't done this knowingly I will be merging this PR, no worries. But please don't repeat it again as it might create problems between participants.

**Pull request merged**
